apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: view-cert
spec:
  version: {{ .TagName }}
  homepage: https://github.com/lmolas/kubectl-view-cert
  shortDescription: View certificate information stored in secrets
  description: |
    View certificate information (version, serial number, issuer, subject 
    and validity) stored in secrets. 
    Supported secret types are kubernetes.io/tls. But you can parse any
    type of secret by specifying secret name and secret key to read.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/lmolas/kubectl-view-cert/releases/download/{{ .TagName }}/kubectl-view-cert_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-view-cert
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/lmolas/kubectl-view-cert/releases/download/{{ .TagName }}/kubectl-view-cert_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-view-cert
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/lmolas/kubectl-view-cert/releases/download/{{ .TagName }}/kubectl-view-cert_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-view-cert
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/lmolas/kubectl-view-cert/releases/download/{{ .TagName }}/kubectl-view-cert_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-view-cert.exe
